name: CI

on:
  push:
    branches:
      - "master"

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Maven Build
        run: mvn clean package